### ISSUE TITLE
ReferenceError: DemoCoinCrowdsale is not defined

### ISSUE THREAD

**Issue by boaerosuke** [llSourcell/what_is_an_initial_coin_offering#1]
```
ReferenceError: DemoCoinCrowdsale is not defined
    at evalmachine.<anonymous>:1:1
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at Object.runInContext (vm.js:89:6)
    at TruffleInterpreter.interpret (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:213786:17)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:538:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:233:10)
```
Is this my installation or does the code need to be changed?

**Comment by flsing** [comment]
same issue

**Comment by dropcunt** [comment]
same issue

**Comment by sheela39** [comment]
truffle(development)> truffle(development)>  DemoCoinCrowdsale.deployed().then(inst => { crowdsale = inst })
ReferenceError: DemoCoinCrowdsale is not defined
truffle(development)> truffle(development)> crowdsale.token().then(addr => { tokenAddress = addr } )
ReferenceError: crowdsale is not defined
